/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.12
 * Generated at: 2019-10-26 22:49:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.formPOST.TPN3.ejercicio1;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class primeraPag_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t\r\n");
      out.write("\tbody\r\n");
      out.write("\t{\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t}\r\n");
      out.write("\t.div-container\r\n");
      out.write("\t{\r\n");
      out.write("\t\twidth: 50%;\r\n");
      out.write("\t\tbackground-color: #333;\r\n");
      out.write("\t\tmargin-left:auto;\r\n");
      out.write("\t\tmargin-right: auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t.formulario\r\n");
      out.write("\t{\r\n");
      out.write("\t\tdisplay: flex;\r\n");
      out.write("\t\tflex-direction:column;\r\n");
      out.write("\t\talign-items: center;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.formulario input\r\n");
      out.write("\t{\r\n");
      out.write("\t\tmax-width: 30vw;\r\n");
      out.write("\t\tbackground-color: transparent;\r\n");
      out.write("\t\tborder: none;\r\n");
      out.write("\t\tborder-bottom: 1px solid white;\r\n");
      out.write("\t\tcolor:inherit;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.conteiner__botoom , .boton\r\n");
      out.write("\t{\r\n");
      out.write("\t\tpadding: 1rem;\r\n");
      out.write("\t\tfont-size: 2rem;\r\n");
      out.write("\t\tbackground-color: blue;\r\n");
      out.write("\t\tborder-bottom: none;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Realizar una aplicaciÃ³n web que calcule el sueldo de un empleado\r\n");
      out.write("solicitando al usuario los siguientes datos:\r\n");
      out.write("â¢ Nombre y apellido\r\n");
      out.write("â¢ DNI\r\n");
      out.write("â¢ CategorÃ­a de empleado (1 al 3)\r\n");
      out.write("â¢ Cantidad de horas trabajadas.\r\n");
      out.write("Se debe calcular el sueldo teniendo en cuenta las siguientes directivas:\r\n");
      out.write("â¦ Consta de un monto bÃ¡sico propio de cada categorÃ­a sumado al producto de\r\n");
      out.write("la cantidad de horas trabajadas y el valor hora de la categorÃ­a.\r\n");
      out.write("[ Sueldo = bÃ¡sico(cat) + cant_horas * Valor-Hora(cat) ]\r\n");
      out.write("â¦ La categorÃ­a 1 tiene un bÃ¡sico de $10.000 mas un valor-hora de $480.\r\n");
      out.write("â¦ La categorÃ­a 2 tiene un bÃ¡sico de $15.000 mas un valor-hora de $520.\r\n");
      out.write("â¦ La categorÃ­a 3 tiene un bÃ¡sico de $14.500 mas un valor-hora de $650.\r\n");
      out.write("Mostrarle al usuario un letrero que incluya DNI, categorÃ­a, cantidad de horas\r\n");
      out.write("trabajadas y el sueldo total calculado. -->\r\n");
      out.write("\t<div class=\"div-container\">\r\n");
      out.write("\t<form action=\"segundaPag.jsp\" method=\"post\" class=\"formulario\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<label for=\"name\">Nombre:</label>\r\n");
      out.write("\t\t<input type=\"text\" id=\"name\" name=\"nombre\">\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<label for=\"surname\">Apellido:</label>\r\n");
      out.write("\t\t<input type=\"text\" id=\"surname\" name=\"apellido\">\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<label for=\"dni\">DNI:</label>\r\n");
      out.write("\t\t<input type=\"text\" id=\"dni\" name=\"DNI\">\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<label for=\"cat\">Categoria Empleado:</label>\r\n");
      out.write("\t\t<input type=\"range\" id=\"cat\" name=\"categoria\" min=\"1\" max=\"3\">\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<label for=\"hs\">Hs. Trabajadas:</label>\r\n");
      out.write("\t\t<input type=\"number\" id=\"hs\" name=\"hstrabajadas\">\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div class=\"conteiner__botoom\">\r\n");
      out.write("\t\t\t<input type=\"submit\" value=\"enviar\" class=\"boton\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
